name: Install Python dependencies
description: Install dependencies from a requirements file into a virtualenv.
runs:
  using: composite
  steps:
    - name: Create Python virtualenv
      run: |
        mkdir -p ~/venv
        python3.7 -m venv ~/venv;
      shell: bash
    - name: Install requirements
      run: ~/venv/bin/pip install -r requirements/development.txt
      shell: bash
