name: Install Python dependencies
description: Install dependencies from a requirements file into a virtualenv.
inputs:
  requirements-file:
    default: "requirements/development.txt"
    description: Requirements file containing a list of Python packages.
    required: False
  virtualenv-location:
    default: "~/venv"
    description: Folder where the virtualenv will be located.
    required: False
runs:
  using: composite
  steps:
    - name: Create Python virtualenv
      run: |
        mkdir -p ${{ inputs.virtualenv-location }}
        python3 -m venv ${{ inputs.virtualenv-location }};
      shell: bash
    - name: Install requirements
      run: ${{ inputs.virtualenv-location }}/bin/pip install -r ${{ inputs.requirements-file }}
      shell: bash
